spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 5n92b24q5jp1mi2ev8f2vpfbna
            client-secret: 1bvodns7i9pp8r0ush9qpirnglqdctcnoslc2s27tfuuujpg8egg
        provider:
          cognito:
            issuer-uri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_7VIUzvZCH

